version: "2"
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: "main"
            # You can use whatever password you like
            MYSQL_PASSWORD: "12345678"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "12345678"
        expose:
            # Opens port 3307 on the container
            - "3307"
    api:
        build: .
        ports:
            - "8000:8000"
        command: "poetry run pytest ${TEST:-} --cov=app --cov-report html:coverage
            tests/"
        environment:
            - ENV_STATE=dev
        volumes:
            - ./coverage:/app/coverage
