version: "2"
services:
    app:
        image: app
        container_name: fastapi_container
        build: .
        ports:
            - "8000:8000"
        expose:
            - "8000"
        volumes:
            - ./:/app
        restart: always
    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: "main"
            # You can use whatever password you like
            MYSQL_PASSWORD: "12345678"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "12345678"
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3307:3306"
        expose:
            # Opens port 3306 on the container
            - "3306"